package producto;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

public class SituacionPaciente extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;
	private static Logger logger = Logger.getLogger(SituacionPaciente.class.getName());
	
    /*
     * Constructor
     */
    public SituacionPaciente() {
        initComponents();
        MenuPrincipalForm.CenteredFrame(this);
    }
    
    /*
     * Limpia el formulario
     */
    public void cleanForm() {
        codField.setText(null);
        medField.setText(null);
        diagField.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        codField = new javax.swing.JTextField();
        medField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        diagField = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        
        this.setTitle("Medicus - Agregar diagnóstico");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Diagnóstico del paciente");

        jLabel2.setText("Complete los siguientes datos:");

        jLabel3.setText("Código del paciente");

        jLabel4.setText("Código del médico");

        jLabel5.setText("Diagnóstico del médico");

        diagField.setColumns(20);
        diagField.setRows(5);
        jScrollPane1.setViewportView(diagField);

        jButton1.setText("Agregar diagnóstico");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(medField, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                    .addComponent(codField)))
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jButton1)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(codField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(medField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     * Agrega un diagnostico, realizando las validaciones correspondientes
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String codpac, codmed, diag;
        
        codpac = codField.getText();
        codmed = medField.getText();      
        diag = diagField.getText();
        
        // validaciones de los campos
        if(codpac.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Error: complete el campo código del paciente","Error",JOptionPane.ERROR_MESSAGE);
            codField.requestFocus();
            logger.info("Error: código de paciente vacío.");
        }
        else if(codmed.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Error: complete el campo código del médico","Error",JOptionPane.ERROR_MESSAGE);
            medField.requestFocus();
            logger.info("Error: código de médico vacío.");
        }
        else if(diag.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Error: complete el campo diagnóstico del médico","Error",JOptionPane.ERROR_MESSAGE);
            diagField.requestFocus();
            logger.info("Error: diagnóstico vacío.");
        }
        // chequeo la existencia del cÃ³digo
        else if(!MenuPrincipalForm.existe("paciente",codpac)) {
            JOptionPane.showMessageDialog(null,"Error: código de paciente inexistente","Error",JOptionPane.ERROR_MESSAGE);
            codField.setText(null);
            codField.requestFocus();
            logger.info("Error: código de paciente inexistente.");
        }
        else if(!MenuPrincipalForm.existe("medico",codmed)) {
            JOptionPane.showMessageDialog(null,"Error: código de médico inexistente","Error",JOptionPane.ERROR_MESSAGE);
            medField.setText(null);
            medField.requestFocus();
            logger.info("Error: código de médico inexistente.");
        }
        else {
            try {
                FileWriter fstream = new FileWriter(MenuPrincipalForm.getRutaArchivoSituacionPacientes(), true);
                BufferedWriter situpac = new BufferedWriter(fstream);

                situpac.write(codpac + "|" + codmed + "|" + diag);
                situpac.newLine();
                situpac.close();

            } catch (IOException e) {}
            logger.info("Diagnóstico agregado.");
            int preg = JOptionPane.showConfirmDialog(null, "Diagnóstico cargado exitosamente, ¿desea agregar otro?", "Aviso", JOptionPane.YES_NO_OPTION);
            if (preg == JOptionPane.YES_OPTION) {
              this.cleanForm();
            }
            else {
               this.dispose();
            }
        }    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SituacionPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SituacionPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SituacionPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SituacionPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Muestra el JFrame
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SituacionPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codField;
    private javax.swing.JTextArea diagField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField medField;
    // End of variables declaration//GEN-END:variables
}
